config/routes.rb
Poorpeoplebank::Application.routes.draw do

  resources :home, only: [:index]

  devise_for :users

  devise_for :admins do
    get "admin", :to => "devise/sessions#new"
    get "admins", :to => "devise/sessions#new"
  end

  namespace :admin do
    resources :admins, only: [:index,:create,:destroy] do
      collection do
        get :settings
        get :suspended
        post :update_settings
        post :update_password
      end
      member do
        post :desuspend
      end
    end
    resources :organizations, only: [:index,:create,:destroy] do
      collection do
        get :suspended
      end
      member do
        post :desuspend
      end
    end
    resources :users, only: [:index,:destroy] do
      collection do
        get :suspended
      end
      member do
        post :desuspend
      end
    end
    resources :borrowers, only: [:index,:create,:destroy]
    resources :cases, only: [:index,:show,:create,:destroy] do
      collection do
        get :suspended
      end
      member do
        post :desuspend
        post :add_installment
        get :installment
        post :add_tags
        post :remove_tag
        post :to_stop_word
      end
    end
    resources :loans, only: [:index,:destroy]
  end

  resources :cases, only: [:index,:show] do
    member do
      get :lend
      post :lender
      post :like
      post :unlike
    end
  end
  
  resources :users, only: [:show] do
    collection do
      get :settings
      post :update_settings
      post :update_password
      get :credit
    end
    member do
      post :withdraw
    end
  end
  resources :borrowers, only: [:show]

  root :to => 'home#index'

end

app/controllers/admin/cases_controller.rb
class Admin::CasesController < ApplicationController
  before_filter :require_admin_login
  
  # GET /admin/cases
  # GET /admin/cases.json
  def index
    @admin_cases = Case.active
    @admin_case = Case.new
  end

  def suspended
    @admin_cases = Case.suspends
  end

  def show
    @case = Case.find(params[:id])
    @installment = Installment.new
  end

  # POST /admin/cases
  # POST /admin/cases.json
  def create
    params[:case][:owner_ids].shift
    @admin_case = Case.new(params[:case])
    @admin_case.creator = current_admin
      if @admin_case.save
        redirect_to admin_cases_url, notice: 'Case was successfully created.'
      else
        render action: "index"
      end
  end

  #POST
  def desuspend
    @case = Case.find(params[:id])
    @case.suspended = false
    @case.save
    redirect_to admin_cases_url 
  end

  # DELETE /admin/cases/1
  # DELETE /admin/cases/1.json
  def destroy
    @case = Case.find(params[:id])
    @case.suspended = true
    @case.save
    redirect_to admin_cases_url 
  end

  #POST
  def add_installment

    unless ((params[:payment_date] == "" && params[:default_date] == 'false' ) || (params[:quantity] == "" && params[:default_inst] == 'false'))
      @case = Case.find(params[:id])
      @installment = Installment.new
      if (params[:default_inst] == 'true')
        @installment.quantity = @case.inst_value
      else
        @installment.quantity = params[:quantity]
        if (params[:extra_inst] == 'true')
          @case.postponed_insts += 1
          @case.save
        end
      end

      # pay_date = params[:payment_date]
      if params[:default_date] == 'true'
        @installment.payment_date = @case.inst_timing(@case.current_inst)
      else
        @installment.payment_date = params[:payment_date]
      end

      late_test = @case.inst_late_by(@installment.payment_date.year,@installment.payment_date.month,@installment.payment_date.day)
      @installment.days_diff = late_test

      @installment.number = @case.current_inst
      @installment.case = @case 
      @installment.creator = current_admin
      @installment.save

      @case.loans.active_payable.each do |loan|
        @payback = PayBack.new
        @payback.quantity = ((loan.percentage / 100.0) * @installment.quantity).round(2)
        @payback.paid_to = loan.user
        @payback.from_installment = @installment
        @payback.from_loan = loan
        @payback.save
      end
      redirect_to admin_case_path(@case), :notice => "Successfully created installment."
    else
      redirect_to admin_cases_path, :alert => "Unsuccessful creation of installment, please try again! \n You must enter Quantity and choose Payment Date."
    end
  end

  def add_tags
    @case = Case.find(params[:id])
    tags_string = params[:tags]
    stop_words = StopWord.in_list
    all_tags = tags_string.filter_tags(stop_words).uniq
    Tag.create_from_array(all_tags,@case.id)
    redirect_to admin_case_path(@case), :notice => "Successfully linked tags to this case."
  end

  def remove_tag
    @case = Case.find(params[:id])
    tag = params[:tag]
    @case.remove_tag(tag)
    redirect_to admin_case_path(@case), :notice => "Successfully unlinked tag to this case."
  end

  def to_stop_word
    @case = Case.find(params[:id])
    tag = params[:tag]
    Tag.to_stop_word(tag)
    redirect_to admin_case_path(@case), :notice => "Successfully changes this tag to stop-word."
  end

end

app/controllers/cases_controller.rb
class CasesController < ApplicationController
  before_filter :require_user_login, :except => [:index, :show]

  # GET /cases
  # GET /cases.json
  def index
    @q=params[:q]
    cas = Case.active.any_of({:title => /#{@q}/i}, {:description => /#{@q}/i})
    if params[:min_time].to_i > 0 && params[:max_time].to_i > 0
      if params[:min_time].to_i >  params[:max_time].to_i
        redirect_to cases_url, :alert => 'Minimum must be smaller than Maximum !'
      else
        cas = cas.where(:inst_months.gte => params[:min_time].to_i, :inst_months.lte =>  params[:min_time].to_i)
      end
    else
      if(params[:min_time].to_i > 0)
        cas = cas.where(:inst_months.gte => params[:min_time].to_i)
      elsif(params[:max_time].to_i > 0)
        cas = cas.where(:inst_months.lte =>  params[:max_time].to_i)
      end
    end
    if(params[:sort])
      case params[:sort]
      when 'newest'
        cas = cas.order_by(:created_at.desc)
      when 'popular'
        cas = cas.sort {|a,b| b.likers.count <=> a.likers.count}
      when 'most_lended'
        cas = cas.sort {|a,b| b.loans.active.count <=> a.loans.active.count}
      when 'almost_collected'
        cas = cas.sort {|a,b| b.collected_perc <=> a.collected_perc}
      end
    end
    @cases = cas.in_columns(3)

    @recomended_cases = Case.get_user_recomendations(current_user).in_columns(4) if current_user
  end

  # GET /cases/1
  # GET /cases/1.json
  def show
    @case = Case.find(params[:id])
    if current_admin
      redirect_to admin_case_path(@case)
    end
  end

  def lend
    redirect_to root_url
  end

  def lender
    @case = Case.find(params[:id])
    @case.likers << current_user
    # loans = Loan.where(:user => current_user, :case => @case, :collected => false)
    loan = Loan.create(params[:loan])
    loan.user = current_user
    loan.case = @case
    loan.save
    @case.tags.each do |tag|
      if TagLike.where(:tag => tag, :liker => current_user).exists?
        tg = TagLike.where(:tag => tag, :liker => current_user).first
        tg.total_likes+=1 
        tg.save
      else
        TagLike.create(:tag => tag,:liker => current_user)
      end
    end
    if @case.save
      redirect_to @case, notice: 'You\'ve successfully lended '+ @case.title
    else
      redirect_to @case, alert: 'Error prevented you from loaning '+ @case.title
    end
  end

  def like
    @case = Case.find(params[:id])
    @case.likers << current_user
    @case.save
    @case.tags.each do |tag|
      if TagLike.where(:tag => tag, :liker => current_user).exists?
        tg = TagLike.where(:tag => tag, :liker => current_user).first
        tg.total_likes+=1 
        tg.save
      else
        TagLike.create(:tag => tag,:liker => current_user)
      end
    end

    if @case.save
      redirect_to @case, notice: 'You\'ve successfully Liked '+ @case.title
    else
      redirect_to @case, alert: 'Error prevented you from Liking '+ @case.title
    end
  end
  
  def unlike
    @case = Case.find(params[:id])
    @case.tags.each do |tag|
      if TagLike.where(:tag => tag, :liker => current_user).exists?
        tg = TagLike.where(:tag => tag, :liker => current_user).first
        tg.total_likes-=1 
        tg.save
      end
    end
    @case.likers.delete(current_user)
    redirect_to @case, notice: 'You\'ve unLiked '+ @case.title
  end

end

app/helpers/admin/cases_helper.rb
module Admin::CasesHelper
end

app/helpers/cases_helper.rb
module CasesHelper
end

app/views/cases/edit.html.erb
<div class="row">
  <div class="span5">
    <div class="well">
      <h3>Edit Case</h3>
      <%= form_for(@case) do |f| %>
        <% if @case.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@case.errors.count, "error") %> prohibited this case from being saved:</h2>

            <ul>
            <% @case.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
            </ul>
          </div>
        <% end %>
        <%= f.text_field :title,:class=>"span4", :placeholder=>"Title"%>
        <%= f.text_field :total_money,:class=>"span4", :placeholder=>"Total Money" %>
        <%= f.text_field :inst_months,:class=>"span4", :placeholder=>"Months to Pay Back" %>
        <%= f.text_field :starting_date, :class=>"span4", :placeholder=>"Starting Date" %>
        <%= f.text_area :description, :class=>"span4", :placeholder=>"Description"  %>
        <%= f.submit "Request", :class=>"btn" %>
      <%end%>
    </div>
    <%= link_to 'Show', @case %> |
    <%= link_to 'Back', cases_path %>
  </div>
</div><!--/row-->

app/views/cases/index.html.erb
<style media="screen" type="text/css">
@media (min-width: 980px) {
.main{padding-top: 90px;}
}
</style>
<% content_for :title do %>
<title>Poor People Bank - Cases</title>
<% end %>
</style>
<div class="span12">
<div class="tabbable"> <!-- Only required for left/right tabs -->
<ul class="nav nav-tabs" >
<li class="active"><a href="#all" data-toggle="tab">All Cases</a></li>
<% if current_user %>
<li><a href="#recomended" data-toggle="tab">Recomended Cases</a></li>
<% end %>
</ul>
<div class="tab-content">
<div class="tab-pane active" id="all">
<% if params[:q] || params[:min_time] || params[:max_time] || params[:sort]%>
<%= link_to "Reset Search", cases_url, :class=>"btn pull-right"%>
<% end %>
<%if @cases.size > 0 %>
<%if @cases[0].size > 0 %>
<div class="row">
<div class="span3">
<form class="form-search">
<div class="input-append">
<%= form_tag cases_path, :authenticity_token => false do%>
<%= text_field_tag :q, nil,:value=>params[:q], :class=>"span2 search-query"%>
<%= submit_tag "Search", :class=>"btn", :style=>'style="padding:5px 13px;'%>
<%end%>
</div>
</form>
<ul class="nav nav-tabs nav-stacked" style="background-color:whitesmoke;">
<li class="active" onClick="$('#sorting').slideToggle();"><a><i class="icon-th-large"></i> Sort By</a></li>
<div class="nav nav-tabs nav-stacked" id="sorting" style="display:none;margin-bottom: 0px;">
<li><%= link_to '<i class="icon-star-empty"></i> Newest'.html_safe, cases_url(:sort => 'newest',:q =>params[:q],:min_time =>params[:min_time],:max_time =>params[:max_time]) %></li>
<li><%= link_to '<i class="icon-heart"></i> Popular'.html_safe, cases_url(:sort => 'popular',:q =>params[:q],:min_time =>params[:min_time],:max_time =>params[:max_time]) %></li>
<li><%= link_to '<i class="icon-shopping-cart"></i> Most Lended'.html_safe, cases_url(:sort => 'most_lended',:q =>params[:q],:min_time =>params[:min_time],:max_time =>params[:max_time]) %></li>
<li><%= link_to '<i class="icon-tasks"></i> Almost Collected'.html_safe, cases_url(:sort => 'almost_collected',:q =>params[:q],:min_time =>params[:min_time],:max_time =>params[:max_time]) %></li>
</div>
<li class="active" onClick="$('#time').slideToggle();"><a><i class="icon-calendar"></i> Repayment Time</a></li>
<div class="nav nav-tabs nav-stacked" id="time" style="display:none;margin-bottom: 0px;">
<li><a><div style="margin-left:30px">
<%= form_tag cases_path, :method => :get, :authenticity_token => false do %>
<%= text_field_tag :min_time, nil,:value=>params[:min_time], :placeholder=>"Min", :class=>"input-mini"%><%= text_field_tag :max_time, nil,:value=>params[:max_time], :placeholder=>"Min", :class=>"input-mini"%>Months<br></div></a>
</li>
</div>
</ul>
<div class="nav-headers pull-right" style="margin-top:-20px;">
<%= submit_tag "Filer", :class=>'btn'%>
<%end%>
</div>
</div>
<div class="span9" id="products">
<!--stack 1-->
<div class="span3" style="margin-left:13px;">
<ul class="thumbnails">
<% @cases[0].each do |pro| %>
<%= render "shared/singlecase", :pro => pro, :shareperc => nil %>
<% end %>
</ul>
</div>
<!--stack 2-->
<div class="span3" style="margin-left:13px;">
<ul class="thumbnails">
<% @cases[1].each do |pro| %>
<%= render "shared/singlecase", :pro => pro, :shareperc => nil %>
<% end %>
</ul>
</div>
<!--stack 3-->
<div class="span3" style="margin-left:13px;">
<ul class="thumbnails">
<% @cases[2].each do |pro| %>
<%= render "shared/singlecase", :pro => pro, :shareperc => nil %>
<% end %>
</ul>
</div>
</div>
<%end%>
<%else%>
<h2><span>Cases</span></h2>
<div class = "well" %>
<% if params[:q] || params[:min_time] || params[:max_time] %>
<p>Couldn't find any results for <%=params[:q]%></p>
<% else %>
<p>There are No Cases Yet.</p>
<% end %>
</div>
<%end%>
</div>
</div>

<% if current_user %>
<div class="tab-pane" id="recomended"> 
<%if @recomended_cases.size > 0 %>
<%if @recomended_cases[0].size > 0 %>
<div class="row">
<div class="span12">
<!--stack 1-->
<div class="span3" style="margin-left:13px;">
<ul class="thumbnails">
<% @recomended_cases[0].each do |pro| %>
<%= render "shared/singlecase", :pro => pro, :shareperc => nil %>
<% end %>
</ul>
</div>
<!--stack 2-->
<div class="span3" style="margin-left:13px;">
<ul class="thumbnails">
<% @recomended_cases[1].each do |pro| %>
<%= render "shared/singlecase", :pro => pro, :shareperc => nil %>
<% end %>
</ul>
</div>
<!--stack 3-->
<div class="span3" style="margin-left:13px;">
<ul class="thumbnails">
<% @recomended_cases[2].each do |pro| %>
<%= render "shared/singlecase", :pro => pro, :shareperc => nil %>
<% end %>
</ul>
</div>
<!--stack 4-->
<div class="span3" style="margin-left:13px;">
<ul class="thumbnails">
<% @recomended_cases[3].each do |pro| %>
<%= render "shared/singlecase", :pro => pro, :shareperc => nil %>
<% end %>
</ul>
</div>
</div>
<%end%>
<%else%>
<h2><span>RecomendedCases</span></h2>
<div class = "well" %>
<p>There are No Cases Yet.</p>
</div>
<%end%>
</div>
</div>
<%end%>

</div> <!-- end tabbable -->
</div>

app/views/cases/lend.html.erb
<% content_for :title do %>
  <title>Poor People Bank - Lend <%=@case.title %></title>
<% end %>

<div class="row">
  <div class="span5">
    <div class="well">
      <h3>Lend Case <%=@case.title%>:</h3>
      <%= form_for(:loan, :url => lender_case_path(@case), :html => { :method => "post" }) do |f| %>
        Quantity:
        <br>
        <%= f.text_field :quantity,:class=>"input-xlarge", :placeholder=>"Quantity"%>
        <br>
        <h3>Address:</h3>
        <br>
        City:
        <br>
        <%= f.text_field :city,:class=>"input-xlarge", :placeholder=>"City"%>
        <br>
        Destrict:
        <br>
        <%= f.text_field :destrict,:class=>"input-xlarge", :placeholder=>"Destrict"%>
        <br>
        Address:
        <br>
        <%= f.text_field :address,:class=>"input-xlarge", :placeholder=>"Address"%>
        <br>             
        Comments:
        <br>
        <%= f.text_field :comments,:class=>"input-xlarge", :placeholder=>"Comments"%>
        <br>
        Type of Loan:
        <br>
          <%= f.radio_button(:donation, :true) %>Donation
          |
          <%= f.radio_button(:donation, :false) %>Repayable Loan
        <br>

        <%= f.submit "Lend", :class=>"btn" %>
      <%end%>
    </div>
    <%= link_to 'Back', cases_path, :class=>"btn" %>
  </div>
</div><!--/row-->

app/views/cases/new.html.erb
<div class="row">
  <div class="span5">
    <div class="well">
      <h3>Create a Case</h3>
      <%= form_for(@case) do |f| %>
        <% if @case.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@case.errors.count, "error") %> prohibited this case from being saved:</h2>

            <ul>
            <% @case.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
            </ul>
          </div>
        <% end %>
        <%= f.text_field :title,:class=>"span4", :placeholder=>"Title"%>
        <%= f.text_field :total_money,:class=>"span4", :placeholder=>"Total Money" %>
        <%= f.text_field :inst_months,:class=>"span4", :placeholder=>"Months to Pay Back" %>
        <%= f.text_field :starting_date, :class=>"span4", :placeholder=>"Starting Date" %>
        <%= f.text_area :description, :class=>"span4", :placeholder=>"Description"  %>
        <%= f.submit "Request", :class=>"btn" %>
      <%end%>
    </div>
    <%= link_to 'Back', cases_path %>
  </div>
</div><!--/row-->

app/views/cases/show.html.erb
<% content_for :title do %>
  <title>Poor People Bank - <%=@case.title%></title>
<% end %>

      <div class="container">
          <div class="wrapper">

            <div class="well">
              <div class="row">
                <div class="span6">

                <div id="myCarousel" class="carousel slide span5">
                  <ol class="carousel-indicators">
                    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                    <li data-target="#myCarousel" data-slide-to="1"></li>
                    <li data-target="#myCarousel" data-slide-to="2"></li>
                  </ol>
                  <!-- Carousel items -->
                  <div class="carousel-inner" style="background-image: url('/images/wild_oliva_dark.png'); border: 5px solid black;">

                  <div class="active item span4" style="height:350px;">
                 <img src="/images/avatar.png" alt="" style="display:block;margin:auto;">
                  </div>

                  <div class="item span4" style="height:350px;">
                 <img src="/images/product.png" alt="" style="display:block;margin:auto;">
                  </div>

                  <div class="item span4" style="height:350px;">
                 <img src="/images/product.png" alt="" style="display:block;margin:auto;">
                  </div>

                  </div>
                  <!-- Carousel nav -->
                  <a class="carousel-control left" href="#myCarousel" data-slide="prev">&lsaquo;</a>
                  <a class="carousel-control right" href="#myCarousel" data-slide="next">&rsaquo;</a>
                </div>

                </div>
                <div class="span5">
                  <h1 align="center"><b><%=@case.title%></b></h1>
                  <h5 align="center"><i class="icon icon-heart"></i> <%=@case.likers.count%> Likers
                    <i class="icon  icon-shopping-cart"></i> <%=@case.loans.active.count%> Doners</h5>

                    <hr>
                    <h3 align="center"></i> Loan: <%=@case.total_money%> LE</h3>
                    <h4 align="center"><i class="icon icon-calendar"></i> <%=@case.inst_months%> Months Repayment + <%= @case.postponed_insts%> Postponed Installments</h4>

                    <div class="form-inline"><h4 align="center"><b><%=@case.collected_perc%>%</b> Raised</h4></div>
                    <div class="progress progress-striped">
                      <div class="bar" style=<%="width:#{@case.collected_perc.to_s}%;"%>></div>
                    </div>
                    <hr>
                    <p><%= @case.description%></p>
                    <hr>
                    <% if user_signed_in? %>
                      <% if @case.likers.include?(current_user)%>
                        <%= link_to 'unLike', unlike_case_path(@case), method: :post,:class=>'btn'%>
                      <% else %>
                        <%= link_to 'Like', like_case_path(@case), method: :post,:class=>'btn'%>
                      <% end %>
                    <% else %>
                      <%= link_to 'Like', like_case_path(@case), method: :post,:class=>'btn'%>
                    <% end %>

                    <% if user_signed_in? %>
                    <!-- Button to trigger modal -->
                      <a href="#myModal" role="button" class="btn btn-primary" data-toggle="modal"> Donate</a>
                    <% else %>
                      <%= link_to 'Donate', lend_case_path(@case) ,:class=>'btn btn-primary'%>
                    <% end %>
                    <a href=<%="http://www.facebook.com/sharer.php?http://poorpeoplebank.herokuapp.com/cases/#{@case.id}"%> class="btn btn-facebook pull-right" target="_blank"><i class="icon icon-facebook"></i> Share</a>
                    <hr>
                    <h4>Loan By: 
                      <%@case.owners.each do |owner| %>
                        <%=link_to owner.name, borrower_path(owner)%>
                      <% end %>
                    </h4>
                  </div>
                </div>
              </div>
            </div>
          </div>

          <div class="container">
            <div class="well">
              <div class="row">
           <div class="span9">
            <div class="tabbable"> <!-- Only required for left/right tabs -->
              <ul class="nav nav-tabs" >
                <li class="active"><a href="#payment" data-toggle="tab">Payment Schedule</a></li>
                <li><a href="#doners" data-toggle="tab">Doners <%= @case.loans.active.count%></a></li>
              </ul>
              <div class="tab-content">
                <div class="tab-pane active" id="payment">
                  <h3>Total Installments: <%= @case.total_insts %></h3>
                  <h3>Remaining Installments: <%= @case.remaining_insts %></h3>
                  <div id="schedule">
                    <table class="table table-striped">
                      <thead>
                        <tr>
                          <th> # </th>
                          <th>Due Date</th>
                          <th>Repayment</th>
                          <th>Status</th>
                          <th>Paid At</th>
                        </tr>
                      </thead>
                      <tbody>

                        <% for i in 1..@case.total_insts %>
                          <tr>
                            <th><%= "##{i}" %></th>
                            <td><%=@case.inst_timing(i).strftime("%B %e, %Y")%></td>
                            <td><%=@case.inst_val(i)%></td>
                            <% sts = @case.inst_status(i) %>
                            <% if sts == 'not_due' %>
                              <td colspan="2">Not Due Yet</td>
<!--                               <td>Not Due Yet</td>
 -->                            <% elsif sts == 'due' %>
                              <td colspan="2">Due But Not Paid Yet</td>
<!--                               <td>Due But Not Paid Yet</td>
 -->                           <% else %>
                              <td>Paid</td>
                              <td><%=sts%></td>
                            <% end %>
                          </tr>
                        <% end %>

                      </tbody>
                    </table>

                  </div>
                </div>
                

                <div class="tab-pane" id="doners"> 
                <% if @case.loans.active.count > 0 %>
                  <% @case.loans.active.each do |loan| %>
                      <div class="span2" style="margin-left:7px;">
                        <ul class="thumbnails">
                          <li class="span2">
                            <div class="wrapper">
                              <div class="thumbnail">
                                <a href=""><img src="/images/avatar.png" alt=""></a>
                                <div><h5><%= link_to loan.user.name, user_path(loan.user)%></h5></div>
                                <h5><i class="icon icon-money"></i>Donated: <b><%=loan.quantity%></b>LE</h5>
                              </div>
                            </div>
                          </li>
                        </ul>
                      </div>
                  <%end%>
                  <% else %>
                  <div class="well">
                    <h3> There are Currently No Doners to this Case!</h3>
                  </div>
                  <% end %>
              </div>

            </div>
            </div> <!-- end tabbable -->
        </div>
</div></div></div>


     
    <!-- Modal -->
    <div id="myModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="margin-top: -5%;">
      <div class="modal-header">

        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3 id="myModalLabel">Lend Case <%=@case.title%>:</h3>

      </div>ـ
      <div class="modal-body">
      <%= form_for(:loan, :url => lender_case_path(@case), :html => { :method => "post" }) do |f| %>
        Quantity:
        <br>
        <%= f.text_field :quantity,:class=>"input-xlarge", :placeholder=>"Quantity"%>
        <br>
        <h3>Address:</h3>
        <br>
        City:
        <br>
        <%= f.text_field :city,:class=>"input-xlarge", :placeholder=>"City"%>
        <br>
        Destrict:
        <br>
        <%= f.text_field :destrict,:class=>"input-xlarge", :placeholder=>"Destrict"%>
        <br>
        Address:
        <br>
        <%= f.text_field :address,:class=>"input-xlarge", :placeholder=>"Address"%>
        <br>        
        Comments:
        <br>
        <%= f.text_field :comments,:class=>"input-xlarge", :placeholder=>"Comments"%>
        <br>
        Type of Loan:
        <br>
          <%= f.radio_button(:donation, :true) %>Donation
          |
          <%= f.radio_button(:donation, :false) %>Repayable Loan
        <br>
      </div>
      <div class="modal-footer">

        <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
        <%= f.submit "Lend", :class=>"btn" %>

      </div>
      <% end %>
    </div>