config/routes.rb
Poorpeoplebank::Application.routes.draw do

  resources :home, only: [:index]

  devise_for :users

  devise_for :admins do
    get "admin", :to => "devise/sessions#new"
    get "admins", :to => "devise/sessions#new"
  end

  namespace :admin do
    resources :admins, only: [:index,:create,:destroy] do
      collection do
        get :settings
        get :suspended
        post :update_settings
        post :update_password
      end
      member do
        post :desuspend
      end
    end
    resources :organizations, only: [:index,:create,:destroy] do
      collection do
        get :suspended
      end
      member do
        post :desuspend
      end
    end
    resources :users, only: [:index,:destroy] do
      collection do
        get :suspended
      end
      member do
        post :desuspend
      end
    end
    resources :borrowers, only: [:index,:create,:destroy]
    resources :cases, only: [:index,:show,:create,:destroy] do
      collection do
        get :suspended
      end
      member do
        post :desuspend
        post :add_installment
        get :installment
        post :add_tags
        post :remove_tag
        post :to_stop_word
      end
    end
    resources :loans, only: [:index,:destroy]
  end

  resources :cases, only: [:index,:show] do
    member do
      get :lend
      post :lender
      post :like
      post :unlike
    end
  end
  
  resources :users, only: [:show] do
    collection do
      get :settings
      post :update_settings
      post :update_password
      get :credit
    end
    member do
      post :withdraw
    end
  end
  resources :borrowers, only: [:show]

  root :to => 'home#index'

end

app/views/admin/admins/edit.html.erb
<h1>Editing admin_admin</h1>

<%= render 'form' %>

<%= link_to 'Show', @admin_admin %> |
<%= link_to 'Back', admin_admins_path %>

app/views/admin/admins/index.html.erb
<% content_for :title do %>
  <title>Poor People Bank - Admins</title>
<% end %>
<div class="row">
  <div class="span12">
    <% if @admin_admin.errors.any? %>
        <div class="alert alert-block">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <p><h4><%= pluralize(@admin_admin.errors.count, "error") %> prohibited this Admin from being Created.</h4></p>
            <ul>
            <% @admin_admin.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
            </ul>
        </div>
    <% end %>

    <%
    if(@admin_admins == nil)
      @admin_admins = Admin.active
    end
    %>

  <h3 align="center">Admins</h3>
  <ul class="nav nav-tabs">
    <li class="active"><a>All Admins</a></li>
    <li><%= link_to 'Suspend Admins', suspended_admin_admins_path%></li>
  </ul>

    <!-- Button to trigger modal -->
    <a href="#myModal" role="button" class="btn pull-right" data-toggle="modal"><i class="icon icon-plus"></i>Create New</a>
     
    <!-- Modal -->
    <div id="myModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="margin-top: -5%;">
      <div class="modal-header">

        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3 id="myModalLabel">Create New Admin</h3>

      </div>ـ
      <div class="modal-body">

      <%= form_for [:admin, @admin_admin] do |f| %>

          Name:
        <br>
          <%= f.text_field :name, :placeholder=>"Name"%>
        <br>
          Email -To be used in login-:
        <br>
          <%= f.text_field :email, :placeholder=>"Email"%>
        <br>
          Belongs to Organization:
        <br>
          <% organizations_array = Organization.all.map { |org| [org.title, org.id] } %>
          <%= f.select(:organization, organizations_array) %>
        <br>

        </div>
        <div class="modal-footer">

          <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
          <%= f.submit "Create",:class=>"btn btn-primary" %>

        </div>
      <% end %>
    </div>
<% if @admin_admins.size > 0 %>
    <table class="table table-hover">
        <thead>
          <tr>
            <th>Name</th>
            <th>Email</th>
            <th>Phone</th>
            <th>Organization</th>
            <th># Created Cases</th>
            <th># Created Borrowers</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
          <% @admin_admins.each do |admin| %>
            <tr>
              <td><%=admin.name%></td>
              <td><%=admin.email%></td>
              <% if admin.phone %>
                <td><%=admin.phone%></td>
              <% else %>
                <td>No Phone</td>
              <% end %>
              <% if admin.organization %>
                <td><%=admin.organization.title%></td>
              <% else %>
                <td>MasterAdmin</td>
              <% end %>
              <td><%=admin.created_cases.count%></td>
              <td><%=admin.created_borrowers.count%></td>
              <td>
                <%= link_to 'Suspend', [:admin,admin],:class=>"btn", method: :delete, data: { confirm: 'Are you sure?' } %>
             </td>
            </tr>

          <% end %>
        </tbody>
    </table>
  </div>
  <% else %>
    <div class="well">
      <h3>There are no admins Yet..</h3>
    </div>
  <% end %>
</div>

app/views/admin/admins/settings.html.erb
<% content_for :title do %>
  <title>Poor People Bank - My Settings</title>
<% end %>
<div class="row">
<div class="span5">
<div class="well">

<% if @admin_admin.errors.any? %>
<div id="error_explanation">
<h2><%= pluralize(@admin_admin.errors.count, "error") %> prohibited these changes from being Saved:</h2>
<ul>
<% @admin_admin.errors.full_messages.each do |msg| %>
<li><%= msg %></li>
<% end %>
</ul>
</div>
<% end %>

<div class="tabbable"> <!-- Only required for left/right tabs -->
<ul class="nav nav-tabs" >
<li class="active"><a href="#info" data-toggle="tab">Update Info</a></li>
<li><a href="#password" data-toggle="tab">Change Password</a></li>
</ul>
<div class="tab-content">
<div class="tab-pane active" id="info">
<h3>Settings</h3>
<%= form_for([:admin,@admin_admin], :url => update_settings_admin_admins_path, :html => { :method => "post" }) do |f| %>
<br>
Name
<br>
<%= f.text_field :name, :placeholder=>"Name"%>
<br>
Phone
<br>
<%= f.text_field :phone, :placeholder=>"Phone"%>
<br>
City
<br>
<%= f.text_field :city, :placeholder=>"City"%>
<br>
<br>
<%= f.submit "Save", :class=>"btn" %>
<%end%>
</div>
<div class="tab-pane" id="password"> 
<h4>Change Password:</h4>
<%= form_for([:admin,@admin_admin], :url => update_password_admin_admins_path, :html => { :method => "post" }) do |f| %>
Password:
<br>
<%= f.password_field :password, :autocomplete => "off"  %>
<br>
Confirm Password:
<br>
<%= f.password_field :password_confirmation %>
<br>
<%= f.submit "Change Password", :class=>"btn" %>
<%end%>
</div>
</div>
</div> <!-- end tabbable -->
</div>
</div>
</div><!--/row-->

app/views/admin/admins/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_admin_admin_path(@admin_admin) %> |
<%= link_to 'Back', admin_admins_path %>

app/views/admin/admins/suspended.html.erb
<% content_for :title do %>
  <title>Poor People Bank - Suspended Admins</title>
<% end %>
<div class="row">
  <div class="span12">

  <h3 align="center">Admins</h3>
  <ul class="nav nav-tabs">
    <li><%= link_to 'All Admins', admin_admins_path%></li>
    <li class="active"><a>Suspended Admins</a></li>
  </ul>

<% if @admin_admins.size > 0 %>
    <table class="table table-hover">
        <thead>
          <tr>
            <th>Name</th>
            <th>Email</th>
            <th>Phone</th>
            <th>Organization</th>
            <th># Created Cases</th>
            <th># Created Borrowers</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
          <% @admin_admins.each do |admin| %>
            <tr>
              <td><%=admin.name%></td>
              <td><%=admin.email%></td>
              <% if admin.phone %>
                <td><%=admin.phone%></td>
              <% else %>
                <td>No Phone</td>
              <% end %>
              <% if admin.organization %>
                <td><%=admin.organization.title%></td>
              <% else %>
                <td>MasterAdmin</td>
              <% end %>
              <td><%=admin.created_cases.count%></td>
              <td><%=admin.created_borrowers.count%></td>
              <td>
                <%= link_to 'Unsuspend', desuspend_admin_admin_path(admin),:class=>"btn", method: :post, data: { confirm: 'Are you sure?' } %>
             </td>
            </tr>

          <% end %>
        </tbody>
    </table>
  </div>
  <% else %>
    <div class="well">
      <h3>There are no Suspended Admins..</h3>
    </div>
  <% end %>
</div>