config/routes.rb
Poorpeoplebank::Application.routes.draw do

  resources :home, only: [:index]

  devise_for :users

  devise_for :admins do
    get "admin", :to => "devise/sessions#new"
    get "admins", :to => "devise/sessions#new"
  end

  namespace :admin do
    resources :admins, only: [:index,:create,:destroy] do
      collection do
        get :settings
        get :suspended
        post :update_settings
        post :update_password
      end
      member do
        post :desuspend
      end
    end
    resources :organizations, only: [:index,:create,:destroy] do
      collection do
        get :suspended
      end
      member do
        post :desuspend
      end
    end
    resources :users, only: [:index,:destroy] do
      collection do
        get :suspended
      end
      member do
        post :desuspend
      end
    end
    resources :borrowers, only: [:index,:create,:destroy]
    resources :cases, only: [:index,:show,:create,:destroy] do
      collection do
        get :suspended
      end
      member do
        post :desuspend
        post :add_installment
        get :installment
        post :add_tags
        post :remove_tag
        post :to_stop_word
      end
    end
    resources :loans, only: [:index,:destroy]
  end

  resources :cases, only: [:index,:show] do
    member do
      get :lend
      post :lender
      post :like
      post :unlike
    end
  end
  
  resources :users, only: [:show] do
    collection do
      get :settings
      post :update_settings
      post :update_password
      get :credit
    end
    member do
      post :withdraw
    end
  end
  resources :borrowers, only: [:show]

  root :to => 'home#index'

end

app/models/organization.rb
class Organization
  include Mongoid::Document
  include Mongoid::Timestamps

  field :title, :type => String
    validates_presence_of :title, :message => "should be entered!"
  field :description, :type => String
    validates_presence_of :description, :message => "should be entered!"
  field :phone, :type => String
    validates_presence_of :phone, :message => "should be entered!"
  field :website, :type => String

  field :city, :type => String
    validates_presence_of :city, :message => "should be entered!"
  field :destrict, :type => String
  field :address, :type => String

  field :suspended, :type => Boolean, :default => :false

  scope :active, where(:suspended => false)
  scope :suspends, where(:suspended => true)

  has_many :admins, class_name: 'Admin'

end

app/controllers/admin/organizations_controller.rb
class Admin::OrganizationsController < ApplicationController
  before_filter :require_admin_login
  
  # GET /admin/organizations
  # GET /admin/organizations.json
  def index
    @admin_organizations = Organization.active
    @admin_organization = Organization.new
  end
  def suspended
    @admin_organizations = Organization.suspends
  end
  # # GET /admin/organizations/1
  # # GET /admin/organizations/1.json
  # def show
  #   @admin_organization = Organization.find(params[:id])
  # end

  # # GET /admin/organizations/new
  # # GET /admin/organizations/new.json
  # def new
  #   @admin_organization = Organization.new
  # end

  # # GET /admin/organizations/1/edit
  # def edit
  #   @admin_organization = Organization.find(params[:id])
  # end

  # POST /admin/organizations
  # POST /admin/organizations.json
  def create
    @admin_organization = Organization.new(params[:organization])
    # @admin_organization.creator = current_admin
    if @admin_organization.save
      redirect_to admin_organizations_url, notice: 'Organization was successfully created.'
    else
      render action: 'index'
    end
  end

  # # PUT /admin/organizations/1
  # # PUT /admin/organizations/1.json
  # def update
  #   @admin_organization = Organization.find(params[:id])

  #     if @admin_organization.update_attributes(params[:organization])
  #       redirect_to @admin_organization, notice: 'Organization was successfully updated.'
  #     else
  #       render action: "edit"
  #     end
  # end
  def desuspend
    @admin_organization = Organization.find(params[:id])
    @admin_organization.suspended = false
    @admin_organization.save
    @admin_organization.admins.each do |admin|
      admin.suspended = false
      admin.save
    end    
    redirect_to admin_organizations_url
  end
  # DELETE /admin/organizations/1
  # DELETE /admin/organizations/1.json
  def destroy
    @admin_organization = Organization.find(params[:id])
    @admin_organization.suspended = true
    @admin_organization.save
    @admin_organization.admins.each do |admin|
      admin.suspended = true
      admin.save
    end
    redirect_to admin_organizations_url
  end
end

app/helpers/admin/organizations_helper.rb
module Admin::OrganizationsHelper
end

app/views/admin/organizations/edit.html.erb
<h1>Editing admin_case</h1>

<%= form_for(@admin_case) do |f| %>
  <% if @admin_case.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@admin_case.errors.count, "error") %> prohibited this admin_case from being saved:</h2>

      <ul>
      <% @admin_case.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= link_to 'Show', @admin_case %> |
<%= link_to 'Back', admin_cases_path %>

app/views/admin/organizations/index.html.erb
<% content_for :title do %>
  <title>Poor People Bank - Organizations</title>
<% end %>
<div class="row">
  <div class="span12">
    <% if @admin_organization.errors.any? %>
        <div class="alert alert-block">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <p><h4><%= pluralize(@admin_organization.errors.count, "error") %> prohibited this Organization from being Created.</h4></p>
            <ul>
            <% @admin_organization.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
            </ul>
        </div>
    <% end %>

    <%
    if(@admin_organizations == nil)
      @admin_organizations = Organization.active
    end
    %>

    <h3 align="center">Organization</h3>
    <ul class="nav nav-tabs">
      <li class="active"><a>All Organizations</a></li>
      <li><%= link_to 'Suspend Organizations', suspended_admin_organizations_path%></li>
    </ul>


    <!-- Button to trigger modal -->
    <a href="#myModal" role="button" class="btn pull-right" data-toggle="modal"><i class="icon icon-plus"></i>Create New</a>
     
    <!-- Modal -->
    <div id="myModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="margin-top: -5%;">
      <div class="modal-header">

        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3 id="myModalLabel">Create New Organization</h3>

      </div>ـ
      <div class="modal-body">

      <%= form_for [:admin, @admin_organization] do |f| %>
        Title:
      <br>
        <%= f.text_field :title, :placeholder=>"Title"%>
      <br>
        Description:
      <br>
        <%= f.text_area :description, :placeholder=>"Description", :rows=>'4'  %>
      <br>
        Phone:
      <br>
        <%= f.text_field :phone, :placeholder=>"Phone"%>
      <br>
        Website:
      <br>
        <%= f.text_field :website, :placeholder=>"Website"%>
      <br>

      <h4>Organization's HeadQuarter's Full Address</h4>
        City:
      <br>
        <%= f.text_field :city,:placeholder=>"Governerate"%>
      <br>
        Destrict:
      <br>
        <%= f.text_field :destrict, :placeholder=>"Destrict"%>
      <br>
        More Address Details:
      <br>
        <%= f.text_field :address, :placeholder=>"Address"%>
      <br>
      </div>
      <div class="modal-footer">

        <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
        <%= f.submit "Create",:class=>"btn btn-primary" %>

      </div>
      <% end %>
    </div>
<% if @admin_organizations.size > 0 %>
    <table class="table table-hover">
        <thead>
          <tr>
            <th>Title</th>
            <th>Phone</th>
            <th>Website</th>
            <th># Admins</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
            <% @admin_organizations.each do |org| %>
              <tr>
                <td><%=org.title%></td>
                <td><%=org.phone%></td>
                <td><%=org.website%></td>
                <td><%=org.admins.count%></td>
                <td>
                  <button class="btn" onclick= <%="showhide('#{org.id.to_s}')"%> > Show/Hide</button>
                  <%= link_to 'Suspend', [:admin,org],:class=>"btn", method: :delete, data: { confirm: 'Are you sure?' } %>
                </td>
              </tr>

              <tr colspan="12" id=<%="#{org.id.to_s}"%> style="display:none;" class="collabsing">
                <td colspan="12">
                    <h4>Address</h4>
                    <p><%="#{org.address}, #{org.destrict}, #{org.city}."%></p>
                    <h4>Description</h4>
                    <p><%=org.description%></p>
                </td>
              </tr>
            <% end %>
        </tbody>
    </table>
  </div>
  <% else %>
    <div class="well">
      <h3>There are no Organizations..</h3>
    </div>
  <% end %>
</div>

app/views/admin/organizations/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_admin_case_path(@admin_case) %> |
<%= link_to 'Back', admin_cases_path %>

app/views/admin/organizations/suspended.html.erb
<% content_for :title do %>
  <title>Poor People Bank - Suspended Organizations</title>
<% end %>
<div class="row">
  <div class="span12">

  <h3 align="center">Organizations</h3>
  <ul class="nav nav-tabs">
    <li><%= link_to 'All Organizations', admin_organizations_path%></li>
    <li class="active"><a>Suspended Organizations</a></li>
  </ul>

<% if @admin_organizations.size > 0 %>
    <table class="table table-hover">
        <thead>
          <tr>
            <th>Title</th>
            <th>Phone</th>
            <th>Website</th>
            <th># Admins</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
            <% @admin_organizations.each do |org| %>
              <tr>
                <td><%=org.title%></td>
                <td><%=org.phone%></td>
                <td><%=org.website%></td>
                <td><%=org.admins.count%></td>
                <td>
                  <button class="btn" onclick= <%="showhide('#{org.id.to_s}')"%> > Show/Hide</button>
                  <%= link_to 'Unsuspend', desuspend_admin_organization_path(org),:class=>"btn", method: :post, data: { confirm: 'Are you sure?' } %>
                </td>
              </tr>

              <tr colspan="12" id=<%="#{org.id.to_s}"%> style="display:none;" class="collabsing">
                <td colspan="12">
                    <h4>Address</h4>
                    <p><%="#{org.address}, #{org.destrict}, #{org.city}."%></p>
                    <h4>Description</h4>
                    <p><%=org.description%></p>
                </td>
              </tr>
            <% end %>
        </tbody>
    </table>
  </div>
  <% else %>
    <div class="well">
      <h3>There are no Suspended Organizations..</h3>
    </div>
  <% end %>
</div>