config/routes.rb
Poorpeoplebank::Application.routes.draw do

  resources :home, only: [:index]

  devise_for :users

  devise_for :admins do
    get "admin", :to => "devise/sessions#new"
    get "admins", :to => "devise/sessions#new"
  end

  namespace :admin do
    resources :admins, only: [:index,:create,:destroy] do
      collection do
        get :settings
        get :suspended
        post :update_settings
        post :update_password
      end
      member do
        post :desuspend
      end
    end
    resources :organizations, only: [:index,:create,:destroy] do
      collection do
        get :suspended
      end
      member do
        post :desuspend
      end
    end
    resources :users, only: [:index,:destroy] do
      collection do
        get :suspended
      end
      member do
        post :desuspend
      end
    end
    resources :borrowers, only: [:index,:create,:destroy]
    resources :cases, only: [:index,:show,:create,:destroy] do
      collection do
        get :suspended
      end
      member do
        post :desuspend
        post :add_installment
        get :installment
        post :add_tags
        post :remove_tag
        post :to_stop_word
      end
    end
    resources :loans, only: [:index,:destroy]
  end

  resources :cases, only: [:index,:show] do
    member do
      get :lend
      post :lender
      post :like
      post :unlike
    end
  end
  
  resources :users, only: [:show] do
    collection do
      get :settings
      post :update_settings
      post :update_password
      get :credit
    end
    member do
      post :withdraw
    end
  end
  resources :borrowers, only: [:show]

  root :to => 'home#index'

end

app/models/user.rb
class User
  include Mongoid::Document
  include Mongoid::Timestamps

  field :name, :type => String
    validates_presence_of :name, :message => "should be entered!"
  field :phone, :type => String
    validates_presence_of :phone, :message => "should be entered!"
  field :location, :type => String
    validates_presence_of :location, :message => "should be entered!"
  # field :city, :type => String
  #   validates_presence_of :city, :message => "should be entered!"
  # field :destrict, :type => String
  #   validates_presence_of :destrict, :message => "should be entered!"
  # field :address, :type => String
  #   validates_presence_of :address, :message => "should be entered!"

  field :suspended, :type => Boolean, :default => :false
  field :show_phone, :type => Boolean, :default => :false
  field :show_location, :type => Boolean, :default => :true

  scope :active, where(:suspended => false)
  scope :suspends, where(:suspended => true)

  field :entity, :type => Boolean
    validates_presence_of :entity, :message => "should be entered!"

  field :default_private_loaning, :type => Boolean, :default => false

  # field :facebook, :type => String
  # field :twitter, :type => String

  field :locale, :type => String, :default => 'en'

  has_many :loans
  
  has_and_belongs_to_many :liked_cases, class_name: "Case", inverse_of: :likers

  has_many :liked_tags, class_name: "TagLike", inverse_of: :liker

  has_many :paybacks, class_name: 'PayBack', inverse_of: :paid_to
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  ## Database authenticatable
  field :email,              :type => String, :default => ""
  field :encrypted_password, :type => String, :default => ""
  
  ## Recoverable
  field :reset_password_token,   :type => String
  field :reset_password_sent_at, :type => Time

  ## Rememberable
  field :remember_created_at, :type => Time

  ## Trackable
  field :sign_in_count,      :type => Integer, :default => 0
  field :current_sign_in_at, :type => Time
  field :last_sign_in_at,    :type => Time
  field :current_sign_in_ip, :type => String
  field :last_sign_in_ip,    :type => String

  ## Confirmable
  # field :confirmation_token,   :type => String
  # field :confirmed_at,         :type => Time
  # field :confirmation_sent_at, :type => Time
  # field :unconfirmed_email,    :type => String # Only if using reconfirmable

  ## Lockable
  # field :failed_attempts, :type => Integer, :default => 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    :type => String # Only if unlock strategy is :email or :both
  # field :locked_at,       :type => Time

  ## Token authenticatable
  # field :authentication_token, :type => String
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_filter :require_admin_login
  
  # GET /admin/users
  # GET /admin/users.json
  def index
    @admin_users = User.active
  end
  def suspended
    @admin_users = User.suspends
  end

  # # GET /admin/users/1
  # # GET /admin/users/1.json
  # def show
  #   @admin_user = User.find(params[:id])
  # end

  # # GET /admin/users/new
  # # GET /admin/users/new.json
  # def new
  #   @admin_user = User.new
  # end

  # # GET /admin/users/1/edit
  # def edit
  #   @admin_user = Admin::User.find(params[:id])
  # end

  # # POST /admin/users
  # # POST /admin/users.json
  # def create
  #   @admin_user = Admin::User.new(params[:admin_user])

  #   if @admin_user.save
  #     format.html { redirect_to @admin_user, notice: 'User was successfully created.' }
  #   else
  #     format.html { render action: "new" }
  #   end
  # end

  # # PUT /admin/users/1
  # # PUT /admin/users/1.json
  # def update
  #   @admin_user = Admin::User.find(params[:id])

  #   respond_to do |format|
  #     if @admin_user.update_attributes(params[:admin_user])
  #       format.html { redirect_to @admin_user, notice: 'User was successfully updated.' }
  #       format.json { head :no_content }
  #     else
  #       format.html { render action: "edit" }
  #       format.json { render json: @admin_user.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end
  def desuspend
    @admin_user = User.find(params[:id])
    @admin_user.suspended = false
    @admin_user.save
    redirect_to admin_users_url
  end
  # DELETE /admin/users/1
  # DELETE /admin/users/1.json
  def destroy
    @admin_user = User.find(params[:id])
    @admin_user.suspended = true
    @admin_user.save
    redirect_to admin_users_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :require_user_login, :except=> [:show]

  def show
    @user = User.find(params[:id])
  end

  def settings
    @user = current_user
    p current_admin
  end

  def update_settings
    @user = current_user
    if @user.update_attributes(params[:user])
      redirect_to settings_users_path, notice: 'Settings Succesfully updated.'
    else
      render action: "settings"
    end
  end

  def update_password
    @user = current_user
    if @user.update_attributes(params[:user])
      # Sign in the user by passing validation in case his password changed
      sign_in @user, :bypass => true
      redirect_to settings_users_path, notice: 'Password Succesfully Changed!'
    else
      render action: "settings"
    end
  end

  def credit
    @user = current_user
  end

  def withdraw
    payback = PayBack.find(params[:id])
    payback.update_attribute(:withdrawn,true)
    redirect_to credit_users_path,:notice=>"You've Succesfully withdrown you PayBack"
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/edit.html.erb
<h1>Editing admin_user</h1>

<%= render 'form' %>

<%= link_to 'Show', @admin_user %> |
<%= link_to 'Back', admin_users_path %>

app/views/admin/users/index.html.erb
<% content_for :title do %>
  <title>Poor People Bank - Users</title>
<% end %>
<div class="row">
  <div class="span12">
  <h3 align="center">Users</h3>
  <ul class="nav nav-tabs">
    <li class="active"><a>All Users</a></li>
    <li><%= link_to 'Suspend Users', suspended_admin_users_path%></li>
  </ul>
<% if @admin_users.size > 0 %>
    <table class="table table-hover">
        <thead>
          <tr>
            <th>Name</th>
            <th>Phone</th>
            <th>Email</th>
            <th>Location</th>
            <th>Entity</th>
            <th># Loans</th>
            <th># Likes</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
          <% @admin_users.each do |user| %>
            <tr>
              <td><%=link_to user.name, user_path(user)%></td>
              <td><%=user.phone%></td>
              <td><%=user.email%></td>
              <td><%=user.location%></td>
              <td><%=user.entity%></td>
              <td><%=user.loans.count%></td>
              <td><%=user.liked_cases.count%></td>
              <td>
                <%= link_to 'Suspend', [:admin,user],:class=>"btn", method: :delete, data: { confirm: 'Are you sure?' } %>
              </td>
            </tr>
          <% end %>
        </tbody>
    </table>
  </div>
  <% else %>
    <div class="well">
      <h3>There are no Users Yet..</h3>
    </div>
  <% end %>
</div>

app/views/admin/users/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_admin_user_path(@admin_user) %> |
<%= link_to 'Back', admin_users_path %>

app/views/admin/users/suspended.html.erb
<% content_for :title do %>
  <title>Poor People Bank - Suspended Users</title>
<% end %>
<div class="row">
  <div class="span12">
  <h3 align="center">Users</h3>
  <ul class="nav nav-tabs">
    <li><%= link_to 'All Users', admin_users_path%></li>
    <li class="active"><a>Suspended Users</a></li>
  </ul>
<% if @admin_users.size > 0 %>
    <table class="table table-hover">
        <thead>
          <tr>
            <th>Name</th>
            <th>Phone</th>
            <th>Email</th>
            <th>Location</th>
            <th>Entity</th>
            <th># Loans</th>
            <th># Likes</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
          <% @admin_users.each do |user| %>
            <tr>
              <td><%=user.name%></td>
              <td><%=user.phone%></td>
              <td><%=user.email%></td>
              <td><%=user.location%> %</td>
              <td><%=user.entity%></td>
              <td><%=user.loans.count%></td>
              <td><%=user.liked_cases.count%></td>
              <td>
                <%= link_to 'Unsuspend', desuspend_admin_user_path(user),:class=>"btn", method: :post, data: { confirm: 'Are you sure?' } %>
              </td>
            </tr>
          <% end %>
        </tbody>
    </table>
  </div>
  <% else %>
    <div class="well">
      <h3>There are no Suspended Users..</h3>
    </div>
  <% end %>
</div>